### ISSUE TITLE
Redirect from less than version 9

### ISSUE THREAD

**Issue by rightaway** [mchristofides/pg_docs_bot#11]
I'm still getting many links in search engines from older versions than 9. Could versions from less than version 9 be redirected too? Maybe google has less older versions but other search engines still show lots of older results, so I end up having to click the Current link regularly.

**Comment by mchristofides** [comment]
Oooh good to know! The main issue was that deprecated features would redirect to a 404, but now the notice (and link) makes that a much more graceful failure case! Screenshot example below.

0.9.2 now adds redirects for versions as far back as 7.0, along with several more deprecated features pages. I got some from [depesz's "why upgrade?" site](https://why-upgrade.depesz.com/show?from=7.2&to=12.2&keywords=deprecated). This could be done more exhaustively, eg #6 

Would you mind sharing a good search engine/search combination for me to see older versions being indexed? 

Please also feel free to add issues for pages that 404, I can add them as exceptions.

Here's how deprecated pages from 7+ will now fail if they're not excluded:
![404-failure-case](https://user-images.githubusercontent.com/10532911/80913357-e56e0100-8d3b-11ea-9322-ebcafe2877bf.png)

**Comment by mchristofides** [comment]
Added in https://github.com/mchristofides/pg_docs_bot/commit/c96886a009ff7c6c30334e169e948fe36e09064e (released as 0.9.2)
